var GAME_LEVELS = [
  ["                                                           J                                       ",
   "                                                        o o o o                                    ",
   "                                                    xxxx x x x xxx                                 ",
   "                 o  xxxxxx                        x       yyyy     x o                             ",
   "            yyyyyy        x                      x       yyyyyy      x o        y                  ",
   "          yyyyyyyyx o     xxxxxxxxxxxxxxxxxxxxxxx         yyyy         x o                         ",
   "            yyyyyy xxx o                                   yy            x o            y          ",
   "                      x  o     o      o   c o             !!!!           xxx                       ",
   "                       xxxxxxxxxxxxxxxxxxxxx       o      !!!!!         xx!xxy                     ",
   "         y                 o    oo             o  xxx     !x!!!x!          x!!!x                   ",
   "                                         o    xxx       !x!!!!!x!         yxx!xx                   ",
   "                       o xxxxx   xx       xxx           !x!!!!!x!             yxxx                 ",
   "                  o xxxx  yyx!!x!yyxxxxxxx              x!!!!!!!x!               xx                ",
   "  xx                x  x   yyx!!!xyy             o o   xx!!!!!!!x!                 x               ",
   "  x           o xxxxx  x   yyx!!!xyy                   x!!!!!!!!!x                  x              ",
   "  x        o    x  xx       yyx!!!xyy            xx j  x!!!!!!!!!x                   x    o       o",
   "  x          xxxx  xx         yx!!!xyyyyyyyyyyyyyyyyy  x!!!!!!!!!x                    x    o  o  o ",
   "  x  @       x xx yyyyyyyyyyyyyx!!!xyy!!!!!!!!!!!!!!y  x!!!!!!!!!x                     x    o   o  ",
   "  xxxxxxxxxxxx  !!!!!!!!!!!!!!yx!!!!!xxxxxxxxxxxxxx!y  x!!!!!!!!!x                      xxxxxxxxx  ",
   "                !!yxxxxxxxxxx!yyx!!!!!xy          y!y  x!!!!!!!!!x                                 ",
   "                !!y         !!!yyx!!!xy            y   x!!!!!!!!!x                                 ",
   "               y!y          !!yyx!!!xy                 x!!!!!!!!!x                                 ",
   "               yy           !yyxxxxxy                  xxxxxxxxxxx                                 ",
   "                                                                                                   ",
   "                                                                                                   "],
  ["                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                             xxxxxxxxxxxxxxxxx                            ",
   "                                                                             !!!!!!!!!!!!!!!!!                    o       ",
   "  @                                                                           !   !    !   !                      o       ",
   " xxx                                                                          !   !    !   !                      o       ",
   "    x                                                                                                             o       ",
   "     x                                                                                                      j     o       ",
   "      x      o     o                                                                                              o       ",
   "       x    xxx   xxx                                                                                             o       ",
   "        x!!!!!!!!!!!!!!x xx   xx                                             o  o  o  o   o                       o       ",
   "         xxxxxxxxxxxxxx x!!o !!x                                                                                  o       ",
   "                        x!!  !!x        yyyyyyyyyy                                                    j           o       ",
   "                        x!!  !!x            yy                                                                    o       ",
   "                        x!! o!!x           yyyy                                                                   o       ",
   "                        x!!  !!x         yyyyyyyy                      xxxjx!!jx!!jx!jx!!jx!j                     o       ",
   "                        x!!  !!x        yyyyyyyyyy                        !!!                !!                   o       ",
   "                        x!!  !!x        yyyyyyyyyy     o                 !!!                 !!!                  o       ",
   "                        x!!  !!x        yyyyyyyyyy   o   o              !!!                  !!!                  o       ",
   "                        x!!o !!x          yyyyyy     o   o             !!!                   !!!!                 o       ",
   "                        x!!  !!x         y     y    o     o            !!!                   !!!!                 o       ",
   "                        x!!  !!x        y       y   o     o       j    !!!!                   !!!!!               o       ",
   "                        x!!  !!x        y       y  o       o      x!!!                     !!!!!                  o       ",
   "                        x!! o!!x        y       y  o       o  !!                           !!!!!                  o       ",
   "                        x!!  !!x        y       y        xxxxxx  !!!                       !!!!!!                 o       ",
   "                        x!!  !!x          o   o   j       !!!    !!!                       !!!!!!                 o       ",
   "                        x!!  !!x      x  xx  xx  xx       !!!    !!!                       !!!!!!!                o       ",
   "                        xxxo xxx     x!!!!!!!!!!!!!x      !!!    !!!                       !!!!!!!                o       ",
   "                        x  o        x!!!!!!!!!!!!!!x      !!!    !!!                       !!!!!!!!               o       ",
   "                        x  o       x!!!!!!!!!!!!!!!x                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                        xxxxxxxxxxx yyyyyyyyyyyyyyy                                                                       "],

  ["                                                                                                                          ",
   "  !!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    ",
   "        !!!!                                                                                                         x    ",
   "          !           !!             !                                                                               x    ",
   "    @                !!      s      !                                                                           r    x    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x    ",
   "           ii                    i                                                                                   x    ",
   "         i         i             i                                                                                   x    ",
   "       i            i        ixxxxxi                                                                                 x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "            i              i i          r              i                i                i                       sss x    ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "     r                                                                                                               x    ",
   "     r                                                                                                               x    ",
   "     r                                                                                                               x    ",
   "     r                                                                                                               x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "                                                                                                                     x    ",
   "   sssss               i                        i                         i                                         ox    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                                                                                                          ",
   "                                                                                                                          "],
   ["                                                                                                                         ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "                                                        x                                                                 ",
   "                                                          x                                   x                           ",
   "                                                            x                               x                             ",
   "                                                              x             @              x                              ",
   "                                                                x           x           x                                 ",
   "                                                                  x       x   x       x                                   ",
   "                                                                    x   x       x   x                                     ",
   "                                                                      x           x                                       ",
   "                                                                                                                          ",
   "                                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
